services:
  mario:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mario
    environment:
      - DISPLAY=$DISPLAY
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ../archive
        target: /opt/mario/archive
      - type: bind
        source: ../logs
        target: /opt/mario/logs
      - type: bind
        source: ../run_logs
        target: /opt/mario/run_logs
      - type: bind
        source: ../src
        target: /opt/mario/src
